package com.thinh.Standee.mapper;

import com.thinh.Standee.dto.request.CreateUserRequest;
import com.thinh.Standee.dto.response.LocationDto;
import com.thinh.Standee.dto.response.UserDto;
import com.thinh.Standee.entity.LocationEntity;
import com.thinh.Standee.entity.RoleEntity;
import com.thinh.Standee.entity.UserEntity;
import com.thinh.Standee.entity.UserLocation;
import com.thinh.Standee.enums.RoleName;
import com.thinh.Standee.repository.LocationRepository;
import com.thinh.Standee.repository.RoleRepository;
import com.thinh.Standee.repository.UserLocationRepository;
import org.mapstruct.*;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.ArrayList;
import java.util.List;

@Mapper(componentModel = "spring", uses = {RoleRepository.class, LocationRepository.class, UserLocationRepository.class})
public abstract class UserMapper {
    @Autowired
    protected LocationRepository locationRepository;
    @Autowired
    protected RoleRepository roleRepository;
    @Autowired
    protected UserLocationRepository userLocationRepository;

    @Mapping(target = "locations", source = "userLocations", qualifiedByName = "userLocationToLocations") // Map userLocations to locations
    @Mapping(target = "role", source = "role.name") // Map RoleEntity to RoleName
    public abstract UserDto toDto(UserEntity userEntity);

    public abstract List<UserDto> toDtoList(List<UserEntity> userEntities);

    @Mapping(target = "id", ignore = true) // ID is generated by the database/JPA
    @Mapping(target = "password", ignore = true) // Password should be handled separately (e.g., encoding)
    @Mapping(target = "role", source = "role", qualifiedByName = "roleNameToRoleEntity") // Custom mapping for Role
    @Mapping(target = "userLocations", ignore = true) // Handled in @AfterMapping
    // BaseEntity fields (if any) are assumed to be handled by JPA auditing or defaults
    // MapStruct implicitly maps: username, email, phone, unit
    public abstract UserEntity toEntity(CreateUserRequest request);

    /**
     * After mapping basic fields, this method populates the UserLocations list.
     * It fetches LocationEntity objects based on IDs from the request,
     * creates UserLocation join entities, and sets the bidirectional relationship.
     */

    @AfterMapping
    protected void mapUserLocations(CreateUserRequest request, @MappingTarget UserEntity userEntity) {
        if (request.getLocationIds() != null && !request.getLocationIds().isEmpty()) {
            for (String locationId : request.getLocationIds()) {
                LocationEntity locationEntity = locationRepository.findById(locationId)
                        .orElseThrow(() -> new RuntimeException("Location not found with ID: " + locationId)); // Example error handling
                UserLocation userLocation = new UserLocation();
                userLocation.setLocation(locationEntity);
                userEntity.addUserLocations(userLocation);
            }
        }
    }

    @Named("userLocationToLocations")
    protected List<LocationDto> userLocationToLocations(List<UserLocation> userLocations) {
        if (userLocations == null) {
            return null;
        }
        List<LocationDto> locationDtos = new ArrayList<>();
        for (UserLocation userLocation : userLocations) {
            LocationEntity locationEntity = userLocation.getLocation();
            if (locationEntity != null) {
                LocationDto locationDto = new LocationDto();
                locationDto.setId(locationEntity.getId());
                locationDto.setName(locationEntity.getName());
                // Add other fields as necessary
                locationDtos.add(locationDto);
            }
        }
        return locationDtos;
    }

    /**
     * Qualifier method to map RoleName enum to RoleEntity using the RoleRepository.
     */
    @Named("roleNameToRoleEntity")
    protected RoleEntity roleNameToRoleEntity(RoleName roleName) {
        if (roleName == null) {
            return null;
        }
        // Fetch the RoleEntity - Add proper error handling as needed
        return roleRepository.findByName(RoleName.valueOf(roleName.name())).orElseThrow(() -> new RuntimeException("Role not found with name: " + roleName)); // Example error handling
    }
}
